// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Station.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include "Station.h"
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>
#include <IceUtil/PopDisableWarnings.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __StationDemo__StationMessage__getMsg_name = "getMsg";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::StationDemo::upCast(::IceProxy::StationDemo::StationMessage* p) { return p; }

void
::IceProxy::StationDemo::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::StationDemo::StationMessage>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::StationDemo::StationMessage;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::StationDemo::StationMessage::getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context* __ctx)
{
    ::IceInternal::Outgoing __og(this, __StationDemo__StationMessage__getMsg_name, ::Ice::Normal, __ctx);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_msg);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    __invoke(__og);
}

::Ice::AsyncResultPtr
IceProxy::StationDemo::StationMessage::begin_getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __StationDemo__StationMessage__getMsg_name, __del, __cookie);
    try
    {
        __result->prepare(__StationDemo__StationMessage__getMsg_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->startWriteParams(::Ice::DefaultFormat);
        __os->write(__p_msg);
        __result->endWriteParams();
        __result->invoke();
    }
    catch(const ::Ice::Exception& __ex)
    {
        __result->abort(__ex);
    }
    return __result;
}

void
IceProxy::StationDemo::StationMessage::end_getMsg(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __StationDemo__StationMessage__getMsg_name);
}

const ::std::string&
IceProxy::StationDemo::StationMessage::ice_staticId()
{
    return ::StationDemo::StationMessage::ice_staticId();
}

::IceProxy::Ice::Object*
IceProxy::StationDemo::StationMessage::__newInstance() const
{
    return new StationMessage;
}

::Ice::Object* StationDemo::upCast(::StationDemo::StationMessage* p) { return p; }

namespace
{
const ::std::string __StationDemo__StationMessage_ids[2] =
{
    "::Ice::Object",
    "::StationDemo::StationMessage"
};

}

bool
StationDemo::StationMessage::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__StationDemo__StationMessage_ids, __StationDemo__StationMessage_ids + 2, _s);
}

::std::vector< ::std::string>
StationDemo::StationMessage::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__StationDemo__StationMessage_ids[0], &__StationDemo__StationMessage_ids[2]);
}

const ::std::string&
StationDemo::StationMessage::ice_id(const ::Ice::Current&) const
{
    return __StationDemo__StationMessage_ids[1];
}

const ::std::string&
StationDemo::StationMessage::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::StationDemo::StationMessage";
    return typeId;
#else
    return __StationDemo__StationMessage_ids[1];
#endif
}

::Ice::DispatchStatus
StationDemo::StationMessage::___getMsg(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::StationDemo::Message __p_msg;
    __is->read(__p_msg);
    __inS.endReadParams();
    getMsg(__p_msg, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __StationDemo__StationMessage_all[] =
{
    "getMsg",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
StationDemo::StationMessage::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__StationDemo__StationMessage_all, __StationDemo__StationMessage_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __StationDemo__StationMessage_all)
    {
        case 0:
        {
            return ___getMsg(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
StationDemo::StationMessage::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
StationDemo::StationMessage::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
StationDemo::__patch(StationMessagePtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::StationDemo::StationMessagePtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::StationDemo::StationMessage::ice_staticId(), v);
    }
}
