// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `Station.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef __Station_h__
#define __Station_h__

#include <IceUtil/PushDisableWarnings.h>
#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/GCObject.h>
#include <Ice/AsyncResult.h>
#include <Ice/Incoming.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <IceUtil/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 306
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace StationDemo
{

class StationMessage;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::StationDemo::StationMessage>&);
::IceProxy::Ice::Object* upCast(::IceProxy::StationDemo::StationMessage*);

}

}

namespace StationDemo
{

class StationMessage;
::Ice::Object* upCast(::StationDemo::StationMessage*);
typedef ::IceInternal::Handle< ::StationDemo::StationMessage> StationMessagePtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::StationDemo::StationMessage> StationMessagePrx;
void __patch(StationMessagePtr&, const ::Ice::ObjectPtr&);

}

namespace StationDemo
{

typedef ::std::vector< ::std::string> myTopicList;

struct Message
{
    ::std::string tpName;
    ::std::string data;
    ::std::string time;
    ::Ice::Int flag;

    bool operator==(const Message& __rhs) const
    {
        if(this == &__rhs)
        {
            return true;
        }
        if(tpName != __rhs.tpName)
        {
            return false;
        }
        if(data != __rhs.data)
        {
            return false;
        }
        if(time != __rhs.time)
        {
            return false;
        }
        if(flag != __rhs.flag)
        {
            return false;
        }
        return true;
    }

    bool operator<(const Message& __rhs) const
    {
        if(this == &__rhs)
        {
            return false;
        }
        if(tpName < __rhs.tpName)
        {
            return true;
        }
        else if(__rhs.tpName < tpName)
        {
            return false;
        }
        if(data < __rhs.data)
        {
            return true;
        }
        else if(__rhs.data < data)
        {
            return false;
        }
        if(time < __rhs.time)
        {
            return true;
        }
        else if(__rhs.time < time)
        {
            return false;
        }
        if(flag < __rhs.flag)
        {
            return true;
        }
        else if(__rhs.flag < flag)
        {
            return false;
        }
        return false;
    }

    bool operator!=(const Message& __rhs) const
    {
        return !operator==(__rhs);
    }
    bool operator<=(const Message& __rhs) const
    {
        return operator<(__rhs) || operator==(__rhs);
    }
    bool operator>(const Message& __rhs) const
    {
        return !operator<(__rhs) && !operator==(__rhs);
    }
    bool operator>=(const Message& __rhs) const
    {
        return !operator<(__rhs);
    }
};

}

namespace Ice
{
template<>
struct StreamableTraits< ::StationDemo::Message>
{
    static const StreamHelperCategory helper = StreamHelperCategoryStruct;
    static const int minWireSize = 7;
    static const bool fixedLength = false;
};

template<class S>
struct StreamWriter< ::StationDemo::Message, S>
{
    static void write(S* __os, const ::StationDemo::Message& v)
    {
        __os->write(v.tpName);
        __os->write(v.data);
        __os->write(v.time);
        __os->write(v.flag);
    }
};

template<class S>
struct StreamReader< ::StationDemo::Message, S>
{
    static void read(S* __is, ::StationDemo::Message& v)
    {
        __is->read(v.tpName);
        __is->read(v.data);
        __is->read(v.time);
        __is->read(v.flag);
    }
};

}

namespace StationDemo
{

class Callback_StationMessage_getMsg_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_StationMessage_getMsg_Base> Callback_StationMessage_getMsgPtr;

}

namespace IceProxy
{

namespace StationDemo
{

class StationMessage : virtual public ::IceProxy::Ice::Object
{
public:

    void getMsg(const ::StationDemo::Message& __p_msg)
    {
        getMsg(__p_msg, 0);
    }
    void getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context& __ctx)
    {
        getMsg(__p_msg, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_getMsg(const ::StationDemo::Message& __p_msg, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_getMsg(__p_msg, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_getMsg(const ::StationDemo::Message& __p_msg, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getMsg(__p_msg, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_getMsg(__p_msg, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_getMsg(__p_msg, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_getMsg(const ::StationDemo::Message& __p_msg)
    {
        return begin_getMsg(__p_msg, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context& __ctx)
    {
        return begin_getMsg(__p_msg, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getMsg(__p_msg, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getMsg(__p_msg, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getMsg(const ::StationDemo::Message& __p_msg, const ::StationDemo::Callback_StationMessage_getMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getMsg(__p_msg, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_getMsg(const ::StationDemo::Message& __p_msg, const ::Ice::Context& __ctx, const ::StationDemo::Callback_StationMessage_getMsgPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_getMsg(__p_msg, &__ctx, __del, __cookie);
    }

    void end_getMsg(const ::Ice::AsyncResultPtr&);
    
private:

    void getMsg(const ::StationDemo::Message&, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_getMsg(const ::StationDemo::Message&, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<StationMessage> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_secure(bool __secure) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_invocationTimeout(int __timeout) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_invocationTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_twoway() const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_oneway() const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_batchOneway() const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_datagram() const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_batchDatagram() const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_compress(bool __compress) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_timeout(int __timeout) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<StationMessage> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<StationMessage*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace StationDemo
{

class StationMessage : virtual public ::Ice::Object
{
public:

    typedef StationMessagePrx ProxyType;
    typedef StationMessagePtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void getMsg(const ::StationDemo::Message&, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___getMsg(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
};

inline bool operator==(const StationMessage& l, const StationMessage& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const StationMessage& l, const StationMessage& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace StationDemo
{

template<class T>
class CallbackNC_StationMessage_getMsg : public Callback_StationMessage_getMsg_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_StationMessage_getMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_StationMessage_getMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_StationMessage_getMsg<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_StationMessage_getMsg<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_StationMessage_getMsg<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_StationMessage_getMsg : public Callback_StationMessage_getMsg_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_StationMessage_getMsg(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_StationMessage_getMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_StationMessage_getMsg<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_StationMessage_getMsg<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_StationMessage_getMsgPtr
newCallback_StationMessage_getMsg(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_StationMessage_getMsg<T, CT>(instance, 0, excb, sentcb);
}

}

#include <IceUtil/PopDisableWarnings.h>
#endif
